services:
  postgres:
    image: postgres:15
    container_name: postgres-poo-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    volumes:
      - postgres-data:/var/lib/postgresql/poo-data
    networks:
      - database

volumes:
  postgres-data:

networks:
  database:
    driver: bridge