name: 'Project Build and Deploy'

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - /tf/**
      - '.github/workflows/infra_**'
    branches:
      - master

jobs:
  build-deploy:
    name: "Build and Deploy"
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/apache/maven/plugins/maven-surefire-plugin
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Archive JAR
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-app
          path: target/*.jar

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key: ${{ env.AWS_ACCESS_KEY }}
          aws-access-secret: ${{ env.AWS_ACCESS_SECRET }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.0
          terraform_wrapper: false

      - name: Fill Environment Variables
        run: |
          TF_VAR_ec2_name: "${{ env.EC2_NAME }}"
          TF_VAR_project_name: "${{ env.PROJECT_NAME }}"
          TF_VAR_region: "${{ env.AWS_REGION }}"

      - name: Terraform Verify
        id: fmt
        run: terraform fmt -check

      - name: Terraform Apply
        id: apply
        run: |
          cd tf
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve