name: "(CI): Verify Build And Plan"

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths-ignore:
      - /tf/**
      - '.github/workflows/infra_**'
    branches:
      - master

jobs:
  continuous-integration:
    name: "Verify Build And Plan"
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4

      - name: Cache Maven packages
        uses: actions/cache@v4

      - name: Build with Maven
        run: mvn clean install

      - name: Archive JAR
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-app
          path: target/*.jar

      - name: Docker Build
        run : |
          docker build -t ci -f Dockerfile .

      - name: Authorization
        run: |
          echo "Your Pull Request has been authorized successfully! 🥳"